//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemeterMachine
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_records
    {
        public int ID { get; set; }
        public int customerID { get; set; }
        public string service_status { get; set; }
        public System.DateTime service_date { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public string customer_states { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
